version: 3.10

services:
  
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD=${DB_PASSWORD}
      POSTGRES_USER = ${DB_USER}
      POSTGRES_DB=${DB_NAME}
