version: 3.10

services:
  
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD=${DB_PASSWORD}
      POSTGRES_USER = ${DB_USER}
      POSTGRES_DB=${DB_NAME}

app:
container_name: app
build: .
command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
