version: 3.10

services:
  
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD=${DB_PASSWORD}
      POSTGRES_USER = ${DB_USER}
      POSTGRES_DB=${DB_NAME}

app:
container_name: app
build: .
command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  - .:/app
ports:
  - 8000:8000
depends_on:
  - db
restart: always  


pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db


